//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_INSUMO_PROVEEDOR
    {
        public int IDDETALLE { get; set; }
        public Nullable<double> STOCK_Kg_ { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public Nullable<System.DateTime> FECHA_PRODUCCION { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public int IDPROVEEDOR { get; set; }
        public int IDINSUMOS { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual INSUMOS INSUMOS { get; set; }
    }
}
