//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public string CODEMPLEADO { get; set; }
        public string APELLIDOS { get; set; }
        public string NOMBRES { get; set; }
        public Nullable<short> DNI { get; set; }
        public string DIRECCION { get; set; }
        public int IDCARGO { get; set; }
    
        public virtual CARGO CARGO { get; set; }
    }
}
