//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSUMOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSUMOS()
        {
            this.DETALLE_INSUMO_PROVEEDOR = new HashSet<DETALLE_INSUMO_PROVEEDOR>();
            this.RECETA = new HashSet<RECETA>();
        }
    
        public int IDINSUMOS { get; set; }
        public string INSUMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_INSUMO_PROVEEDOR> DETALLE_INSUMO_PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECETA> RECETA { get; set; }
    }
}
