//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        public int IDRECETA { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public int IDPRODUCTO { get; set; }
        public int IDINSUMOS { get; set; }
    
        public virtual INSUMOS INSUMOS { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
